-- Generic Constants Parameter Table
CREATE TABLE IF NOT EXISTS generic_constants_param
(
    id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,                            -- Auto-generated by DB
    dtype         VARCHAR(255)              NOT NULL,                                    -- Type of constant (Roles, Gender, etc.)
    code          VARCHAR(255)              NOT NULL,                                    -- The code for the constant value (e.g., SuperAdmin, Admin)
    description   TEXT,                                                                  -- Description of the constant value
    version_id    BIGINT UNSIGNED DEFAULT 1 NOT NULL,                                    -- Version ID for tracking changes
    active_status TINYINT(1)      DEFAULT 1 NOT NULL,                                    -- Active status (1: Active, 0: Inactive)
    created_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,                             -- Insertion date
    updated_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, -- Modification date
    UNIQUE (dtype, code, active_status)                                                  -- Ensure dtype, code, and active_status combination is unique
);


-- Insert Roles Seed Data
INSERT INTO generic_constants_param (dtype, code, description, version_id, active_status)
VALUES ('Role', 'SuperAdmin', 'Has full access and control over all features and settings in the system', 1, 1),
       ('Role', 'Admin', 'Has access to most features, but limited administrative powers compared to SuperAdmin', 1, 1),
       ('Role', 'Member', 'Standard user with basic access to features and limited control over groups', 1, 1),
       ('Role', 'Guest', 'User with limited access, typically for view-only purposes', 1, 1);

INSERT INTO generic_constants_param (dtype, code, description, version_id, active_status)
VALUES ('Permission', 'CD', 'Permission to create a new group', 1, 1),
       ('Permission', 'DG', 'Permission to delete a group', 1, 1),
       ('Permission', 'MG', 'Permission to modify group details (e.g., name, description)', 1, 1),
       ('Permission', 'AM', 'Permission to add members to a group', 1, 1),
       ('Permission', 'RM', 'Permission to remove members from a group', 1, 1),
       ('Permission', 'TO', 'Permission to transfer group ownership', 1, 1),
       ('Permission', 'VT', 'Permission to view transactions within a group', 1, 1);

-- Insert Gender Seed Data
INSERT INTO generic_constants_param (dtype, code, description, version_id, active_status)
VALUES ('Gender', 'Male', 'Represents male gender', 1, 1),
       ('Gender', 'Female', 'Represents female gender', 1, 1),
       ('Gender', 'Other', 'Represents non-binary or other gender identities', 1, 1);

-- Insert Record Status Seed Data
INSERT INTO generic_constants_param (dtype, code, description, version_id, active_status)
VALUES ('RecordStatus', 'Active', 'Record is active and available for use', 1, 1),
       ('RecordStatus', 'Inactive', 'Record is inactive and not available for use', 1, 1),
       ('RecordStatus', 'Deleted', 'Record has been deleted and is no longer in use', 1, 1);


-- Users Table
CREATE TABLE IF NOT EXISTS users
(
    id             BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, -- Auto-generated by DB (Row ID)
    user_id        VARCHAR(255) UNIQUE           NOT NULL,     -- Backend assigns user_id
    name           VARCHAR(255)                  NOT NULL,
    username       VARCHAR(255) UNIQUE DEFAULT NULL,
    email          VARCHAR(255) UNIQUE           NOT NULL,
    phone_no       VARCHAR(15) UNIQUE  DEFAULT NULL,
    gender_id      BIGINT UNSIGNED     DEFAULT NULL,           -- References the ID in generic_constants_param (Gender)
    status_id      BIGINT UNSIGNED     DEFAULT NULL,           -- References the ID in generic_constants_param (RecordStatus)
    password_hash  VARCHAR(255)                  NOT NULL,
    email_verified TINYINT(1)          DEFAULT 0,              -- 0: Not Verified, 1: Verified
    version_id     BIGINT UNSIGNED     DEFAULT 1 NOT NULL,
    created_at     TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP           DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (gender_id) REFERENCES generic_constants_param (id)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    FOREIGN KEY (status_id) REFERENCES generic_constants_param (id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- Groups Table
CREATE TABLE IF NOT EXISTS ams_groups
(
    id                BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, -- Auto-generated by DB (Row ID)
    group_id          VARCHAR(255) UNIQUE       NOT NULL,         -- System-generated group ID (assigned by backend)
    group_name        VARCHAR(255)              NOT NULL,
    group_description TEXT,
    created_by        BIGINT UNSIGNED           NOT NULL,         -- Foreign key to users (Group Owner) (assigned by backend)
    status_id         BIGINT UNSIGNED DEFAULT NULL,               -- References the ID in generic_constants_param (RecordStatus)
    version_id        BIGINT UNSIGNED DEFAULT 1 NOT NULL,
    created_at        TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (status_id) REFERENCES generic_constants_param (id),
    FOREIGN KEY (created_by) REFERENCES users (id)                -- Backend assigns user_id
);

-- Group Members Table
CREATE TABLE IF NOT EXISTS group_members
(
    id         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, -- Auto-generated by DB (Row ID)
    group_id   VARCHAR(255)              NOT NULL,         -- Backend assigns group_id
    user_id    VARCHAR(255)              NOT NULL,         -- Backend assigns user_id
    role_id    BIGINT UNSIGNED           NOT NULL,         -- References the ID in generic_constants_param (Roles)
    settings   JSON            DEFAULT NULL,               -- Stores permissions override for a specific user in the group
    status_id  BIGINT UNSIGNED DEFAULT NULL,               -- References the ID in generic_constants_param (RecordStatus)
    version_id BIGINT UNSIGNED DEFAULT 1 NOT NULL,
    created_at TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (status_id) REFERENCES generic_constants_param (id),
    FOREIGN KEY (role_id) REFERENCES generic_constants_param (id),
    FOREIGN KEY (group_id) REFERENCES ams_groups (group_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id),
    UNIQUE (group_id, user_id)                             -- Ensures a user can only be in a group once
);

-- Transactions Table
CREATE TABLE IF NOT EXISTS transactions
(
    id             BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, -- Auto-generated by DB (Row ID)
    group_id       VARCHAR(255)              NOT NULL,         -- Backend assigns group_id
    expense_amount DECIMAL(10, 2)            NOT NULL,
    purchase_item  TEXT                      NOT NULL,         -- Item purchased
    paid_by        VARCHAR(255)              NOT NULL,         -- Backend assigns user_id (the user who paid)
    version_id     BIGINT UNSIGNED DEFAULT 1 NOT NULL,
    txn_time       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES ams_groups (group_id),
    FOREIGN KEY (paid_by) REFERENCES users (user_id)
);

-- Virtual Accounts Table
CREATE TABLE IF NOT EXISTS virtual_accounts
(
    id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, -- Auto-generated by DB (Row ID)
    user_id       VARCHAR(255)              NOT NULL,         -- Backend assigns user_id
    group_id      VARCHAR(255)              NOT NULL,         -- Backend assigns group_id
    balance       DECIMAL(10, 2)  DEFAULT 0.00,               -- Balance in the group for each user
    total_balance DECIMAL(10, 2)  DEFAULT 0.00,               -- Cumulative balance across all ams_groups
    version_id    BIGINT UNSIGNED DEFAULT 1 NOT NULL,
    created_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (user_id),
    FOREIGN KEY (group_id) REFERENCES ams_groups (group_id),
    UNIQUE (user_id, group_id)                                -- Ensures a single virtual account per user per group
);

-- Password Resets Table
CREATE TABLE IF NOT EXISTS password_resets
(
    id              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, -- Auto-generated by DB (Row ID)
    email           VARCHAR(255)              NOT NULL,
    token           VARCHAR(255)              NOT NULL,
    version_id      BIGINT UNSIGNED DEFAULT 1 NOT NULL,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    expiration_time TIMESTAMP,                                  -- Time until token expires
    used_at         TIMESTAMP       DEFAULT NULL,               -- Time when token was used
    status_id       BIGINT UNSIGNED DEFAULT NULL,               -- References the ID in generic_constants_param (RecordStatus)
    FOREIGN KEY (status_id) REFERENCES generic_constants_param (id),
    UNIQUE (email, token)                                       -- Ensure unique token per email
);

-- Login Sessions Table
CREATE TABLE IF NOT EXISTS login_sessions
(
    id                 BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, -- Auto-generated by DB (Row ID)
    user_id            VARCHAR(255)              NOT NULL,         -- Backend assigns user_id
    token              VARCHAR(255)              NOT NULL,         -- Token for session management
    device_info        TEXT,                                       -- Info about the user's device
    ip_address         VARCHAR(255)    DEFAULT NULL,               -- IP address of the login
    login_time         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    last_activity_time TIMESTAMP       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status_id          BIGINT UNSIGNED DEFAULT NULL,               -- References the ID in generic_constants_param (RecordStatus)
    version_id         BIGINT UNSIGNED DEFAULT 1 NOT NULL,
    expiry_time TIMESTAMP DEFAULT NULL,
    FOREIGN KEY (user_id) REFERENCES users (user_id),
    FOREIGN KEY (status_id) REFERENCES generic_constants_param (id),
    UNIQUE (user_id)                                               -- Ensures only one active session per user
);

-- Activity Logs Table
CREATE TABLE IF NOT EXISTS activity_logs
(
    id         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, -- Auto-generated by DB (Row ID)
    user_id    VARCHAR(255)              NOT NULL,         -- Backend assigns user_id
    action     VARCHAR(255)              NOT NULL,
    details    TEXT,
    version_id BIGINT UNSIGNED DEFAULT 1 NOT NULL,
    created_at TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- User Roles Table
CREATE TABLE IF NOT EXISTS user_roles
(
    id         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, -- Auto-generated by DB (Row ID)
    user_id    VARCHAR(255)              NOT NULL,         -- Backend assigns user_id
    group_id   VARCHAR(255)              NOT NULL,         -- Backend assigns group_id
    role_id    BIGINT UNSIGNED           NOT NULL,         -- References the ID in generic_constants_param (Roles)
    version_id BIGINT UNSIGNED DEFAULT 1 NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (user_id),
    FOREIGN KEY (group_id) REFERENCES ams_groups (group_id),
    FOREIGN KEY (role_id) REFERENCES generic_constants_param (id)
);



CREATE TABLE IF NOT EXISTS role_permissions
(
    role_id       BIGINT UNSIGNED NOT NULL, -- Foreign key to roles (generic_constants_param with dtype = 'Role')
    permission_id BIGINT UNSIGNED NOT NULL, -- Foreign key to permissions (generic_constants_param with dtype = 'Permission')
    PRIMARY KEY (role_id, permission_id),   -- Composite primary key for the role-permission pair
    FOREIGN KEY (role_id) REFERENCES generic_constants_param (id)
        ON DELETE CASCADE,                  -- Reference to roles in generic_constants_param
    FOREIGN KEY (permission_id) REFERENCES generic_constants_param (id)
        ON DELETE CASCADE                   -- Reference to permissions in generic_constants_param
);

CREATE TABLE otp_verification
(
    id          INT AUTO_INCREMENT PRIMARY KEY,
    email       VARCHAR(255) NOT NULL,
    otp_code    VARCHAR(6)   NOT NULL,
    created_at  TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    expired_at  TIMESTAMP    NOT NULL,
    is_verified TINYINT(1) DEFAULT 0,
    UNIQUE (email, otp_code)
);


###################   Indexes #############
-- Indexes for generic_constants_param table
CREATE INDEX idx_dtype_code_status ON generic_constants_param (dtype, code, active_status);
CREATE INDEX idx_dtype ON generic_constants_param (dtype);
CREATE INDEX idx_code ON generic_constants_param (code);

-- Indexes for users table
CREATE INDEX idx_user_id ON users (user_id);
CREATE INDEX idx_username ON users (username);
CREATE INDEX idx_email ON users (email);
CREATE INDEX idx_phone_no ON users (phone_no);
CREATE INDEX idx_gender_id ON users (gender_id);
CREATE INDEX idx_status_id ON users (status_id);

-- Indexes for ams_groups table
CREATE INDEX idx_group_id ON ams_groups (group_id);
CREATE INDEX idx_created_by ON ams_groups (created_by);
CREATE INDEX idx_status_id_group ON ams_groups (status_id);

-- Indexes for group_members table
CREATE INDEX idx_group_id_user_id ON group_members (group_id, user_id);
CREATE INDEX idx_role_id ON group_members (role_id);
CREATE INDEX idx_status_id_member ON group_members (status_id);

-- Indexes for transactions table
CREATE INDEX idx_group_id_txn ON transactions (group_id);
CREATE INDEX idx_paid_by ON transactions (paid_by);
CREATE INDEX idx_txn_time ON transactions (txn_time);

-- Indexes for virtual_accounts table
CREATE INDEX idx_user_id_group_id ON virtual_accounts (user_id, group_id);
CREATE INDEX idx_group_id_virtual ON virtual_accounts (group_id);
CREATE INDEX idx_user_id_virtual ON virtual_accounts (user_id);

-- Indexes for password_resets table
CREATE INDEX idx_email_token ON password_resets (email, token);
CREATE INDEX idx_status_id_reset ON password_resets (status_id);

-- Indexes for login_sessions table
CREATE INDEX idx_user_id_session ON login_sessions (user_id);
CREATE INDEX idx_token ON login_sessions (token);
CREATE INDEX idx_ip_address ON login_sessions (ip_address);
CREATE INDEX idx_status_id_session ON login_sessions (status_id);

-- Indexes for activity_logs table
CREATE INDEX idx_user_id_activity ON activity_logs (user_id);
CREATE INDEX idx_action ON activity_logs (action);
CREATE INDEX idx_created_at_activity ON activity_logs (created_at);

-- Indexes for user_roles table
CREATE INDEX idx_user_id_group_role ON user_roles (user_id, group_id, role_id);
CREATE INDEX idx_group_id_role ON user_roles (group_id, role_id);
CREATE INDEX idx_role_id_user ON user_roles (role_id, user_id);

-- Indexes for role_permissions table
CREATE INDEX idx_role_id_permission ON role_permissions (role_id, permission_id);
CREATE INDEX idx_role_id ON role_permissions (role_id);
CREATE INDEX idx_permission_id ON role_permissions (permission_id);



# ##################### Seed Data #####################


-- Insert Role-Permission Mapping Data
INSERT INTO role_permissions (role_id, permission_id)
VALUES
    -- Mapping SuperAdmin role to permissions
    ((SELECT id FROM generic_constants_param WHERE dtype = 'Role' AND code = 'SuperAdmin' LIMIT 1),
     (SELECT id FROM generic_constants_param WHERE dtype = 'Permission' AND code = 'CD' LIMIT 1)), -- create_group

    ((SELECT id FROM generic_constants_param WHERE dtype = 'Role' AND code = 'SuperAdmin' LIMIT 1),
     (SELECT id FROM generic_constants_param WHERE dtype = 'Permission' AND code = 'DG' LIMIT 1)), -- delete_group

    ((SELECT id FROM generic_constants_param WHERE dtype = 'Role' AND code = 'SuperAdmin' LIMIT 1),
     (SELECT id FROM generic_constants_param WHERE dtype = 'Permission' AND code = 'MG' LIMIT 1)), -- modify_group

    ((SELECT id FROM generic_constants_param WHERE dtype = 'Role' AND code = 'SuperAdmin' LIMIT 1),
     (SELECT id FROM generic_constants_param WHERE dtype = 'Permission' AND code = 'AM' LIMIT 1)), -- add_member

    ((SELECT id FROM generic_constants_param WHERE dtype = 'Role' AND code = 'SuperAdmin' LIMIT 1),
     (SELECT id FROM generic_constants_param WHERE dtype = 'Permission' AND code = 'RM' LIMIT 1)), -- remove_member

    ((SELECT id FROM generic_constants_param WHERE dtype = 'Role' AND code = 'SuperAdmin' LIMIT 1),
     (SELECT id FROM generic_constants_param WHERE dtype = 'Permission' AND code = 'TO' LIMIT 1)), -- transfer_ownership

    ((SELECT id FROM generic_constants_param WHERE dtype = 'Role' AND code = 'SuperAdmin' LIMIT 1),
     (SELECT id FROM generic_constants_param WHERE dtype = 'Permission' AND code = 'VT' LIMIT 1)), -- view_transactions

    -- Mapping Admin role to permissions
    ((SELECT id FROM generic_constants_param WHERE dtype = 'Role' AND code = 'Admin' LIMIT 1),
     (SELECT id FROM generic_constants_param WHERE dtype = 'Permission' AND code = 'MG' LIMIT 1)), -- modify_group

    ((SELECT id FROM generic_constants_param WHERE dtype = 'Role' AND code = 'Admin' LIMIT 1),
     (SELECT id FROM generic_constants_param WHERE dtype = 'Permission' AND code = 'AM' LIMIT 1)), -- add_member

    ((SELECT id FROM generic_constants_param WHERE dtype = 'Role' AND code = 'Admin' LIMIT 1),
     (SELECT id FROM generic_constants_param WHERE dtype = 'Permission' AND code = 'RM' LIMIT 1)), -- remove_member

    -- Mapping Member role to permissions
    ((SELECT id FROM generic_constants_param WHERE dtype = 'Role' AND code = 'Member' LIMIT 1),
     (SELECT id FROM generic_constants_param WHERE dtype = 'Permission' AND code = 'VT' LIMIT 1)); -- view_transactions


