 db.host=localhost
 db.name=testdb
 db.username=root
 db.password=root
 log.path=logs/log.log
 log.level=DEBUG
 email.host.name=smtp.gmail.com
 email.username=amsjavatechno@gmail.com
 email.password=aflnxpdpwoqbkdhl
 email.encryption=tls
 email.port=587
 email.from.address=amsjavatechno@gmail.com
 email.title=JavaTechno Ams Portal
